### PR TITLE
updated pull request from visvash attri

### PR DESCRIPTION
**Pull request by visvash**
Kindly review my updated pull request. @Shubhanshu07 
I have put in all my efforts and created a new pull request this time.

### CODE REVIEW

**Comment by agshubhs** [comment]
@visvash  Looks good but still minute changes are required.

**Comment by visvash** [comment]
please merge the pull request @Shubhanshu07

**Comment by visvash** [comment]
i have made the changes as suggested @Shubhanshu07 ...kindly merge the pull request.

**Comment by agshubhs** [comment]
@visvash  Do the changes as  mentioned.

**Comment by visvash** [comment]
I have made all the changes as suggested. Kindly accept the pull request @Shubhanshu07

**Comment by visvash** [comment]
please review the pull request @sh

**Comment by visvash** [comment]
please review my pull request @Shubhanshu07

**Comment by visvash** [comment]
i have made the commits @Shubhanshu07  please review sir...

**Comment by agshubhs** [comment]
@visvash  Finally looking nice

**Comment by visvash** [comment]
Thank you so much sir.

**Pull request merged**
